config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'

  resources :lists do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, except: %i[destroy]

  # CREATE
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully created.'
    else
      render :new
    end
  end

  # DELETE
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, except: %i[index new create]

  # CREATE
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # READ
  def index
    @lists = List.all
  end

  def show
  end

  # UPDATE
  def edit
  end

  def update
    @list.update(list_params)

    redirect_to lists_path
  end

  # DELETE
  def destroy
    @list.destroy

    redirect_to lists_path, notice: 'List was successfully deleted.'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">

  <div class="card-category card-big card-category-big m-5 p-4">

  <h1> Add movie to  <%= @list.name %> </h1>

    <%= simple_form_for [@list, @bookmark] do |f| %>
      <% if @bookmark.errors.any? %>
        <div class="alert alert-danger">
          <h5>You must correct these errors</h5>
          <ul>
            <% @bookmark.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.input :comment %>
      <%= f.association :movie, collection: Movie.all - @list.movies %>
      <%= f.submit class: 'btn btn-primary' %> or
      <%= link_to 'Cancel', list_path(@list), class: 'btn btn-danger' %>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;400;700&display=swap" rel="stylesheet">
  </head>

  <body>

      <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :photo, as: :file %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

    <%= f.button :submit, class: "form-actions btn btn-primary"%>
    or
    <%= link_to 'Cancel', lists_path, class: "btn btn-danger"%>

<% end %>

app/views/lists/edit.html.erb
<div class="container">

  <div class="card-category card-big card-category-big m-5 p-4">

    <h1>Edit your <%= @list.name %> list</h1>

    <%= render 'form', list: @list %>

  </div>

</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1867&q=80);">
  <div class="container">
    <h1>Your Movie Lists</h1>
    <p class="mt-2">Start by making a list</p>
    <%= link_to 'New List', new_list_path, class: 'btn-medium mt-1' %>
  </div>
</div>


<% if notice.present? %>
  <p id="notice" class="alert alert-success m-3">
    <%= notice %>
  </p>
<% end %>

<h2 class="m-3"> <%= @lists.empty? ? "You haven't saved any lists yet..." : "Your Lists:" %> </h2>

  <ul>
  <% @lists.each do |list| %>
    <li>
      <div  class = "card-category-list m-5"style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.5)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>)">
      <%= link_to list.name.upcase, list, class: "m-3" %>
      <%= link_to 'Edit', edit_list_path(list), class: "btn-medium ml-5" %>
      <%= link_to 'Delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-medium-danger m-2"  %>
        </div>
   </li>
  <% end %>
  </ul>
<br>

app/views/lists/new.html.erb
<div class="container">

  <div class="card-category card-big card-category-big m-5 p-4">

    <h1>New List</h1>

    <%= render 'form', list: @list %>

  </div>

</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>);">
  <div class="container">
    <h1 class="mb-3"> <%= @list.name.upcase %> </h1>

    <%= link_to 'Edit this list', edit_list_path, class: 'btn btn-primary mr-3' %>


    <%= link_to list_path(@list), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this list?' } do %>
      Delete this list
    <% end %>

  </div>
</div>



<h2 class="m-3"> <%= @list.movies.empty? ? "You haven't saved any movies yet..." : "Your Bookmarks:" %> </h2>

<ul>
  <% @list.bookmarks.each do |bookmark| %>
  <li>
    <div class="card-product m-3">
      <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title %>
        <div class="card-product-infos">
          <h2><%= bookmark.movie.title %> | <%= bookmark.movie.rating %> </h2>
          <p><%= bookmark.comment %></p>
          <%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: 'Are you sure you want to delete this bookmark?', },  class: 'delete-btn' %>
        </div>
    </div>
  </li>
  <% end %>
</ul>

 <%= link_to new_list_bookmark_path(@list), class: 'btn btn-primary m-3' do %>
    Add movie
  <% end %>

<%= link_to 'Back', lists_path, class: 'btn btn-secondary' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="#">Apply now</a>
  </div>
</div>